services:
  - type: web
    name: autoshop-pro-django
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn workshop_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DATABASE_URL
        fromDatabase:
          name: autoshop-db
          property: connectionString

databases:
  - name: autoshop-db
    databaseName: autoshop
    user: autoshop_user
    plan: free
