# Generated by Django 6.0.3 on 2026-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Original cost from supplier', max_digits=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Your selling price to customer', max_digits=10),
        ),
    ]
