# Generated by Django 6.0.3 on 2026-07-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_part_buying_price_alter_part_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.CharField(choices=[('Genuine', 'Genuine'), ('OEM', 'OEM'), ('Aftermarket', 'Aftermarket'), ('Used', 'Used'), ('Local', 'Local')], default='Genuine', max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Brand/manufacturer e.g. Toyota, Bosch', max_length=100),
        ),
    ]
