# Generated by Django 6.0.3 on 2026-07-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invoice_amount_paid_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='mileage',
            field=models.CharField(blank=True, default='', help_text='Optional vehicle mileage at time of service', max_length=30),
        ),
        migrations.CreateModel(
            name='JobLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='e.g. Self Motor Labour, Oil Change Labour', max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_labours', to='core.jobcard')),
            ],
        ),
    ]
