# Generated by Django 6.0.3 on 2026-07-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_job_labour_and_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('default_price', models.DecimalField(decimal_places=2, help_text='Default price/labour cost in Rs.', max_digits=10)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
